BEGIN
  FOR C IN (SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE '||C.TABLE_NAME||' CASCADE CONSTRAINTS');
  END LOOP;
END;
/


BEGIN
	FOR S IN (SELECT SEQUENCE_NAME FROM USER_SEQUENCES)
	LOOP
	 EXECUTE IMMEDIATE 'DROP SEQUENCE ' || S.SEQUENCE_NAME;
	END LOOP;
END;
/

CREATE TABLE PROJECT (
  ID VARCHAR2(20) NOT NULL,
  LABEL  VARCHAR2(40) NOT NULL,
  IDPROJECTMANAGER VARCHAR2(20),
  IDSCRUMMASTER  VARCHAR2(20),
  CONSTRAINT PROJECTPK PRIMARY KEY (ID)
  USING INDEX TABLESPACE TBS_DATA
)
TABLESPACE TBS_DATA;

CREATE TABLE PROJECTAFFECTATION(
	IDPROJECT VARCHAR2(20) NOT NULL,
	IDPERSON VARCHAR2(20) NOT NULL,
	IDROLE VARCHAR2(10) NOT NULL,
	DATESTART DATE,
	ENDDATE DATE,
	ACTIVITYPERCENTAGE NUMBER DEFAULT 100,
	CONSTRAINT PROJECTAFFECTATIONPK PRIMARY KEY (IDPROJECT, IDPERSON, IDROLE, DATESTART)
)
TABLESPACE TBS_DATA;

CREATE TABLE PERSON (
  ID VARCHAR2(20) NOT NULL,
  NAME NVARCHAR2(40) NOT NULL,
  SURNAME NVARCHAR2(40) NOT NULL,
  IDCOMPANY VARCHAR2(10),
  IDROLE VARCHAR2(10),
  DATEENTREE DATE default '01-JAN-16',    
  DATESORTIE DATE,
  SENIORITY NUMBER DEFAULT 0,
  CONSTRAINT PERSONPK PRIMARY KEY (ID)
  USING INDEX TABLESPACE TBS_DATA
)
TABLESPACE TBS_DATA;




CREATE TABLE COMPANY (
  ID VARCHAR2(10) NOT NULL,
  NAME VARCHAR2(30) NOT NULL,
  CONSTRAINT COMPANYPK PRIMARY KEY (ID)
  USING INDEX TABLESPACE TBS_DATA
)
TABLESPACE TBS_DATA;


CREATE TABLE INTERVIEW (
  ID INT NOT NULL,
  STATUS VARCHAR2(10) NOT NULL,
  KIND NVARCHAR2(40) NOT NULL,
  ASSESSEDDATE VARCHAR2(8) NOT NULL,
  DURATION VARCHAR2(8),
  IDMAINASSESSOR VARCHAR2(20) NOT NULL,
  IDSECONDARYASSESSOR VARCHAR2(20),
  IDASSESSED VARCHAR2(210) NOT NULL,
  COMPANYPREMIUM VARCHAR2(10),
  GOALSPREMIUM VARCHAR2(10),
  SALARYRAISE VARCHAR2(15),
  CONSTRAINT INTERVIEWPK PRIMARY KEY (ID)
  USING INDEX TABLESPACE TBS_DATA
)
TABLESPACE TBS_DATA;

CREATE TABLE INTERVIEWCOMMENT (
	ID INT NOT NULL,
	IDINTERVIEW INT NOT NULL,
	IDPERSON VARCHAR2(20) NOT NULL,
	KIND NVARCHAR2(15),
	TEXT NVARCHAR2(200) NOT NULL,
	CONSTRAINT COMMENTSPK PRIMARY KEY (ID)
	USING INDEX TABLESPACE TBS_DATA
)
TABLESPACE TBS_DATA;

CREATE TABLE CONCEPTIONREVIEW (
	ID INT NOT NULL,
	KIND VARCHAR2(10) NOT NULL,
	REVIEWNB INT NOT NULL,
	STATUS VARCHAR2(10) DEFAULT 'TODO',
	IDPROJECT VARCHAR2(20) NOT NULL,
	SUBJECT NVARCHAR2(200) NOT NULL,
	IDCONCEPTOR VARCHAR2(20) NOT NULL,
	EFFECTIVEDATE NVARCHAR2(8),
	URLSPEC NVARCHAR2(100),
	URLCONCEPTION NVARCHAR2(100),
	CONSTRAINT CONCEPTIONREVIEWPK PRIMARY KEY (ID)
)
TABLESPACE TBS_DATA;

CREATE TABLE REVIEWER (
	ID INT NOT NULL,
	IDREVIEW INT NOT NULL,
	IDREVIEWER VARCHAR2(20) NOT NULL,
	SENIORITY NUMBER DEFAULT 0,
	CONSTRAINT REVIEWERPK PRIMARY KEY (ID, IDREVIEW, IDREVIEWER)
	USING INDEX TABLESPACE TBS_DATA
)
TABLESPACE TBS_DATA;

CREATE TABLE REVIEW_PAIR (
	LEFT_ID VARCHAR2(20) NOT NULL,
	RIGHT_ID VARCHAR2(20) NOT NULL,
	PERIOD VARCHAR2(6) NOT NULL,
	CONSTRAINT REVIEW_PAIR_PK PRIMARY KEY (LEFT_ID, RIGHT_ID, PERIOD)	
	USING INDEX TABLESPACE TBS_DATA
)
TABLESPACE TBS_DATA;

CREATE SEQUENCE itw_seq;
CREATE SEQUENCE comments_seq;
CREATE SEQUENCE conception_seq;
CREATE SEQUENCE reviewer_seq;


CREATE OR REPLACE TRIGGER itw_id 
BEFORE INSERT ON INTERVIEW 
FOR EACH ROW

BEGIN
  SELECT itw_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER comments_id 
BEFORE INSERT ON INTERVIEWCOMMENT
FOR EACH ROW

BEGIN
  SELECT comments_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER conception_id 
BEFORE INSERT ON CONCEPTIONREVIEW
FOR EACH ROW

BEGIN
  SELECT conception_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER reviewer_id 
BEFORE INSERT ON REVIEWER
FOR EACH ROW

BEGIN
  SELECT reviewer_seq.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;
/
